### ISSUE TITLE
New release after boot issues now being fixed?

### ISSUE THREAD

**Issue by frittentheke** [steamhaus/goat#5]
Hey there. First of all thank you very very much for taking over the project to keep it maintained and current!

May I kindly ask if you intend to do another release with all open issues related to startup (https://github.com/steamhaus/goat/issues/2) now resolved? I'd gladly take it out for a spin as we did ran into some of those (now fixed) effects ourselves from time to time.

**Comment by bilco105** [comment]
Hi @frittentheke, 

I've released v1.0.4 for you. Apologies for the delay.

Thanks
